### PR TITLE
A bit cleaner

### PR DESCRIPTION
**Pull request by ToolB0xx**
- Added colors and implemented them as best as I could (Not well, I presume). The --no-color flag has also been added to --help
- Added a check to warn user of insufficient funds due to not taking market_buy_inflation into account
- Added strings to check for to make sure if the user wants to buy, he buys (For typos)
- Added config variable for toggling on/off the Bittrex API data and UUID printing out in the console from polling active order. Mainly to prevent spam, and for features I think would be useful to implement later (And clarity)
- Added important user feedback so they know when and why things happen (Like telling them why the process exited when they did "X" thing)
- Added a console.log stating that Ctrl + S is a thing. Added Ctrl + S usage to README.md as well as other things
- Added some little changes in spacing within config.example.js
- Removed the constant "GAIN DOES NOT PASS CONFIGURED THRESHOLD, NOT SELLING." Seems redundant, as the console already prints sufficient data for the user to understand his/her threshold hasn't yet been met (Might possible add it back in if I ever figure out how to update certain lines in the console)
- Cleaned up the output a bit, added tabs to line up integer values nicely, added new lines where they were needed, spaced out much more, and legible

### CODE REVIEW

**Comment by davidmckenzie** [comment]
😍

**Comment by davidmckenzie** [comment]
@ToolB0xx this might be what you mentioned on discord: https://stackoverflow.com/questions/17309749/node-js-console-log-is-it-possible-to-update-a-line-rather-than-create-a-new-l

We could use that to display the updating information, and send the existing outputs to a log file for review.

IMO, we keep the last 10 price checks visible just so that users have a bit of reference point to the price movement if they look away for a bit, but flexible on that...

Can probably have a play with it tomorrow night :)

**Comment by davidmckenzie** [comment]
Oh damn, I just found that library we were looking for, too: https://www.npmjs.com/package/terminal-kit

**Comment by ToolB0xx** [comment]
Awesome I'll look into it, thanks

**Comment by ToolB0xx** [comment]
@davidmckenzie terminal kit introduces this nice function I'd like to implement, so people an scroll up in the terminal but have the non-polling data stay still, while only the low part of the console window scrolls. This would allow the user not only to see the last 10 price checks, but all of them. One small problem, it is not compatible with linux terminals. Up to you if you'd like me to implement it anyways. Otherwise I'll keep looking at a way to show at least 10 price checks in the terminal window.

- .scrollingRegion(top,bottom): limit all scrolling operations to the region between top and bottom line included (Linux Console doesn't support it)

**Comment by ToolB0xx** [comment]
## CHANGED

- Added a persistent gui-type thingy. All info shown and entered at the beginning of the programs execution will remain there to reduce the pain of scrolling up to see what users entered in at, what coin they bought, etc. 
- "Current Sell Evaluation" and "Total Gain" values are now on one line for legibility. 
- Program now keeps track of the last 10 price updates during execution, although I'd like to make a config variable for that in the future. 
- Persistent fields around scrolling price update history have been added to notify the user that one, you can hit Ctrl + S at any time to sell low, and two, what type of trade they are currently in (Live trade or Fake trade)
- Coin field added at top, right before Current ask/bid/last prices are printed, to let users know what coin they typed in? (Hopefully they know)

## ISSUES

- This update has NOT been tested for LIVE TRADING. As of right now it works well for Fake Buys. I'll figure it out eventually once I actually have funds to test it out, but for now I'll wait on this. (This doesn't mean you can't use it for live trades, just that I don't know where everything is going to print out, and it might get messy. If you do happen to do a live trade and encounter random stuff that you don't think should happen, please let me know)
- Right now the console must be AT LEAST 68x30 characters
- Need to make sure that the config variable I added (show_orderdata) actually works, and if so, figure out where it's printing after these new changes
- When resizing the console window, if you drag it in too small everything gets really messed up. It will correct over time, however, but less legible.

## TODO

- A lot of things, really.

**Pull request merged**
